<?php if(Mage::registry('current_category')->getId() == 215 or Mage::registry('current_category')->getId() == 31):?>
	<div id="colunas9" class="c-banner-toner-po-refil">
		<img src="<?php echo $this->getUrl('') ?>banners/categorias/banner-toner-po-refil.png" alt="Toner Pó Refil" title="Toner Pó Refil" />
		<img src="<?php echo $this->getUrl('') ?>banners/categorias/banner-toner-po-refil-faixa.png" alt="Clique no Fabricante do Toner Pó Refil" title="Clique no Fabricante do Toner Pó Refil" />
		<ul>
			<li><a href="<?php echo $this->getUrl('') ?>samsung/refil-toner-samsung" class="c-samsung" title="Toner Pó Refil Samsung" alt="Toner Pó Refil Samsung">samsung</a></li>
			<li><a href="<?php echo $this->getUrl('') ?>canon/toner-po-refil" class="c-canon" title="Toner Pó Refil Canon" alt="Toner Pó Refil Canon">canon</a></li>
			<li><a href="<?php echo $this->getUrl('') ?>sharp/toner-po-refil" class="c-sharp" title="Toner Pó Refil Sharp" alt="Toner Pó Refil Sharp">sharp</a></li>
			<li><a href="<?php echo $this->getUrl('') ?>brother/toner-po-refil" class="c-brother" title="Toner Pó Refil Brother" alt="Toner Pó Refil Brother">brother</a></li>
			<li><a href="<?php echo $this->getUrl('') ?>hp/toner-po-refil" class="c-hp" title="Toner Pó Refil HP" alt="Toner Pó Refil HP">hp</a></li>
			<li><a href="<?php echo $this->getUrl('') ?>ricoh/toner-po-refil" class="c-ricoh" title="Toner Pó Refil Ricoh" alt="Toner Pó Refil Ricoh">ricoh</a></li>
			<li><a href="<?php echo $this->getUrl('') ?>lexmark/toner-po-refil" class="c-lexmark" title="Toner Pó Refil Lexmark" alt="Toner Pó Refil Lexmark">lexmark</a></li>
			<li><a href="<?php echo $this->getUrl('') ?>xerox/toner-po-refil" class="c-xerox" title="Toner Pó Refil Xerox" alt="Toner Pó Refil Xerox">xerox</a></li>
			<li><a href="<?php echo $this->getUrl('') ?>kyocera/toner-po-refil" class="c-kyocera" title="Toner Pó Refil Kyocera" alt="Toner Pó Refil Kyocera">kyocera</a></li>
			<li><a href="<?php echo $this->getUrl('') ?>toner-minolta/toner-po-refil" class="c-konica-minolta" title="Toner Pó Refil Konica Minolta" alt="Toner Pó Refil Konica Minolta">konica minolta</a></li>
			<li><a href="<?php echo $this->getUrl('') ?>toshiba/toner-po-refil" class="c-toshiba" title="Toner Pó Refil Toshiba" alt="Toner Pó Refil Toshiba">toshiba</a></li>
		</ul>
	</div>
<?php endif; ?>

<?php if(Mage::registry('current_category')->getId() == 216 or Mage::registry('current_category')->getId() == 45):?>
	<div id="colunas9" class="c-banner-toner-po-refil">
		<img src="<?php echo $this->getUrl('') ?>banners/categorias/banner-cartucho-toner.png" alt="Catucho Katun" title="Catucho Katun" />
		<img src="<?php echo $this->getUrl('') ?>banners/categorias/banner-cartucho-toner-faixa.png" alt="Clique no Fabricante do Catucho" title="Clique no Fabricante do Catucho" />
		<ul>
			<li><a href="<?php echo $this->getUrl('') ?>samsung/cartucho-de-toner-samsung" class="c-samsung" title="Catucho Katun Samsung" alt="Catucho Katun Samsung">samsung</a></li>
			<li><a href="<?php echo $this->getUrl('') ?>canon/cartucho-de-toner" class="c-canon" title="Catucho Katun Canon" alt="Catucho Katun Canon">canon</a></li>
			<li><a href="<?php echo $this->getUrl('') ?>sharp/cartucho-de-toner" class="c-sharp" title="Catucho Katun Sharp" alt="Catucho Katun Sharp">sharp</a></li>
			<li><a href="<?php echo $this->getUrl('') ?>brother/cartucho-de-toner" class="c-brother" title="Catucho Katun Brother" alt="Catucho Katun Brother">brother</a></li>
			<li><a href="<?php echo $this->getUrl('') ?>hp/cartucho-de-toner" class="c-hp" title="Catucho Katun HP" alt="Catucho Katun HP">hp</a></li>
			<li><a href="<?php echo $this->getUrl('') ?>ricoh/cartucho-de-toner" class="c-ricoh" title="Catucho Katun Ricoh" alt="Catucho Katun Ricoh">ricoh</a></li>
			<li><a href="<?php echo $this->getUrl('') ?>lexmark/cartucho-de-toner" class="c-lexmark" title="Catucho Katun Lexmark" alt="Catucho Katun Lexmark">lexmark</a></li>
			<li><a href="<?php echo $this->getUrl('') ?>xerox/cartucho-de-toner" class="c-xerox" title="Catucho Katun Xerox" alt="Catucho Katun Xerox">xerox</a></li>
			<li><a href="<?php echo $this->getUrl('') ?>kyocera/cartucho-de-toner" class="c-kyocera" title="Catucho Katun Kyocera" alt="Catucho Katun Kyocera">kyocera</a></li>
			<li><a href="<?php echo $this->getUrl('') ?>toner-minolta/cartucho-de-toner" class="c-konica-minolta" title="Catucho Katun Konica Minolta" alt="Catucho Katun Konica Minolta">konica minolta</a></li>
			<li><a href="<?php echo $this->getUrl('') ?>toshiba/cartucho-de-toner" class="c-toshiba" title="Catucho Katun Toshiba" alt="Catucho Katun Toshiba">toshiba</a></li>
		</ul>
	</div>
<?php endif; ?>

<?php
    $_helper    = $this->helper('catalog/output');
    $_category  = $this->getCurrentCategory();
    $_imgHtml   = '';
    if ($_imgUrl = $_category->getImageUrl()) {
        $_imgHtml = '<p class="category-image"><img src="'.$_imgUrl.'" alt="'.$this->htmlEscape($_category->getName()).'" title="'.$this->htmlEscape($_category->getName()).'" /></p>';
        $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
    }
?>

    <?php if($this->IsRssCatalogEnable() && $this->IsTopCategory()): ?>
        <a href="<?php echo $this->getRssLink() ?>" class="link-rss"><?php echo $this->__('Subscribe to RSS Feed') ?></a>
    <?php endif; ?>

    	<p class="fs-14"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></p>

    <?php if($_imgUrl): ?>
	<div id="colunas9">
    	<?php echo $_imgHtml ?>
	</div>
    <?php endif; ?>

<?php if($this->isContentMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>

<?php elseif($this->isMixedMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>
    <?php echo $this->getProductListHtml() ?>

<?php else: ?>
    <?php echo $this->getProductListHtml() ?>
<?php endif; ?>

<?php if($_description=$this->getCurrentCategory()->getDescription()): ?>
	<div id="colunas9">
	<?php echo $_helper->categoryAttribute($_category, $_description, 'description') ?>
	</div>
<?php endif; ?>
<script type="text/javascript">
var google_tag_params = {
//ecomm_prodid: '', 
ecomm_pagetype: "category"//,
//ecomm_totalvalue: ''
};
</script>