<?php
/**
 *
 * @category   Inovarti
 * @package    Inovarti_Pagarme
 * @author     Suporte <suporte@inovarti.com.br>
 */
?>
<?php echo $this->htmlEscape($this->getMethod()->getTitle()) ?>

<?php if(trim($this->getBoletoUrl()) != false): ?>
<br />
<a href="<?php echo $this->getBoletoUrl() ?>" target="_blank"><?php echo $this->__('Click here to print your Boleto') ?></a>
<?php else: ?>
<br />
<?php echo $this->__('Your Boleto is being generated and will be ready soon') ?>
<?php endif ?>

<?php echo $this->getChildHtml()?>
