<div id="pagarme-mask" style="display:none;">
    <p class="loader" id="pagarme-mask-loader">
        <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>"
             alt="<?php echo Mage::helper('core')->__('Loading...') ?>" />
            <br />
            <?php echo Mage::helper('core')->__('Please wait...') ?>
    </p>
</div>

<div id="pagarme-overlay" style="display:none;"></div>

