<?php
/**
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2012 Magento Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
    <p class="hello fs-20 txt bold"><?php echo $this->__('Hello, %s!', $this->htmlEscape($this->getCustomerName())) ?></p>
    <br />
    <p class="txt fs-14">Esse &eacute; o seu Painel Geral. Aqui, voc&ecirc; poder&aacute; acompanhar seus pedidos e editar suas informa&ccedil;&otilde;es de cadastro.</p>
