<label for="<?php echo $this->getFieldId('gender')?>" class="txt fs-12 f-l <?php if ($this->isRequired()) echo 'required' ?>">
	<?php //echo '<sup>*</sup>' ?><?php echo $this->__('Gender') ?>&nbsp;
</label>
<div class="data_area">
    <select id="<?php echo $this->getFieldId('gender')?>" name="<?php echo $this->getFieldName('gender')?>" title="<?php echo $this->__('Gender') ?>"<?php if ($this->isRequired()):?> class="validate-select required-entry "<?php endif; ?> <?php echo $this->getFieldParams() ?>>
        <?php $options = Mage::getResourceSingleton('customer/customer')->getAttribute('gender')->getSource()->getAllOptions();?>
        <?php $value = $this->getGender();?>
        <?php foreach ($options as $option):?>
            <option value="<?php echo $option['value'] ?>"<?php if ($option['value'] == $value) echo ' selected="selected"' ?>><?php echo $option['label'] ?></option>
        <?php endforeach;?>
    </select>
</div>