<?php
/**
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2012 Magento Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * Temlate for Mage_Customer_Block_Address_Book block
 * @var $test Mage_Customer_Block_Address_Book
 */
?>
<div id="colunas9">
    <h1 class="cor bold"><?php echo $this->__('Address Book') ?></h1>
    <br />
    <button type="button" title="<?php echo $this->__('Add New Address') ?>" class="button bt radius cor-sec tt-u fs-14 bold td-n" onclick="window.location='<?php echo $this->getAddAddressUrl() ?>';"><?php echo $this->__('Add New Address') ?></button>
</div>
<div id="colunas9">
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

        <h2 class="txt bold fs-14"><?php echo $this->__('Default Addresses') ?></h2>
        <br />
        <ol>
        <?php if($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultBilling()): ?>
            <li class="item">
                <h3 class="txt fs-14 bold"><?php echo $this->__('Default Billing Address') ?></h3><a class="cor fs-12" href="<?php echo $this->getAddressEditUrl(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>">(<?php echo $this->__('Change Billing Address') ?>)</a>
                <br />
                <p class="txt fs-14"><?php echo $this->getAddressHtml(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?></p>
           </li>
           <br />
        <?php else: ?>
            <li class="item">
                <h3 class="txt fs-14 bold"><?php echo $this->__('Default Billing Address') ?></h3>
                <p class="txt fs-14"><?php echo $this->__('You have no default billing address in your address book.') ?></p>
            </li>
            <br />
        <?php endif ?>

        <?php if($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultShipping()): ?>
            <li class="item">
                <h3 class="txt fs-14 bold"><?php echo $this->__('Default Shipping Address') ?></h3><a class="cor fs-12" href="<?php echo $this->getAddressEditUrl(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>">(<?php echo $this->__('Change Shipping Address') ?>)</a>
                <p class="txt fs-14"><?php echo $this->getAddressHtml(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?></p>
            </li>
            <br />
        <?php else: ?>
            <li class="item empty">
                <h3 class="txt fs-14 bold"><?php echo $this->__('Default Shipping Address') ?></h3>
                <p class="txt fs-14"><?php echo $this->__('You have no default shipping address in your address book.') ?></p>
            </li>
            <br />
        <?php endif ?>
        </ol>

        <h2 class="txt fs-14 bold"><?php echo $this->__('Additional Address Entries') ?></h2>
        <ol>
        <?php if($_pAddsses = $this->getAdditionalAddresses()): ?>
            <?php foreach($_pAddsses as $_address): ?>
            <li class="item">
                <p class="txt fs-14"><?php echo $this->getAddressHtml($_address) ?></p>
                <a class="cor fs-12" href="<?php echo $this->getUrl('customer/address/edit', array('id'=>$_address->getId())) ?>"><?php echo $this->__('Edit Address') ?></a> <span class="separator">|</span> <a href="#" class="link-remove cor fs-12" onclick="return deleteAddress('<?php echo $_address->getId() ?>');"><?php echo $this->__('Delete Address') ?></a>
            </li>
            <?php endforeach; ?>
        <?php else: ?>
            <li class="item empty">
                <p class="txt fs-14"><?php echo $this->__('You have no additional address entries in your address book.') ?></p>
            </li>
        <?php endif ?>
        </ol>
</div>
<div id="colunas9">
   <!-- <a class="cor fs-12" href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a>-->
</div>

<script type="text/javascript">
//<![CDATA[
    function deleteAddress(addressId) {
        if(confirm('<?php echo $this->__('Are you sure you want to delete this address?') ?>')) {
            window.location='<?php echo $this->getDeleteUrl() ?>id/'+addressId;
        }
        return false;
    }
//]]>
</script>
