<?php
/**
* @E-Commercewebdesign.co.uk
*/
$_product = $this->getProduct();
$_tierPrices = $this->getTierPrices();
$_finalPriceInclTax = $this->helper('tax')->getPrice($_product, $_product->getFinalPrice(), true);

$_weeeTaxAmount = Mage::helper('weee')->getAmountForDisplay($_product);
if (Mage::helper('weee')->typeOfDisplay($_product, array(1,2,4))) {
$_weeeTaxAttributes = Mage::helper('weee')->getProductWeeeAttributesForDisplay($_product);
}

?>
<?php if (count($_tierPrices) > 0): ?>
	<div class="clear"></div><br />
	<div class="tierprice">
	<?php if ($this->getInGrouped()): ?>
		<?php $_tierPrices = $this->getTierPrices($_product); ?>
	<?php endif; ?>

	<?php Mage::helper('weee')->processTierPrices($_product, $_tierPrices); ?>
	<?php $_tierPrices = array_values($_tierPrices); ?>
	<?php foreach ($_tierPrices as $_price): ?>
		<?php echo '<p class="fs-14">Acima de <strong>'.$_price['price_qty'].'</strong> unidades &mdash; '.$_price['formated_price'].' (cada)</p>'; ?>
	<?php endforeach ?>
	</div>
<br /><div class="h-r f-l d-b"></div><br />
<?php endif;?>
