<?php
/**
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2012 Magento Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
USAGE:

Simple:

<?php echo $this->getLayout()->createBlock('customer/widget_dob')
   ->setDate($this->getCustomer()->getDob())
   ->toHtml() ?>

For checkout/onepage/billing.phtml:

<?php echo $this->getLayout()->createBlock('customer/widget_dob')
   ->setDate($this->getCustomer()->getDob())
   ->setFieldIdFormat('billing:%s')
   ->setFieldNameFormat('billing[%s]')
   ->toHtml() ?>

NOTE: Regarding styles - if we leave it this way, we'll move it to boxes.css
      Alternatively we could calculate widths automatically using block input parameters.
*/

/**
 * @see Mage_Customer_Block_Widget_Dob
 */
?>
<label for="<?php echo $this->getFieldId('month')?>"class="txt fs-12<?php if ($this->isRequired()) echo ' required' ?>"><?php if ($this->isRequired()) echo '<em>*</em>' ?><?php echo $this->__('Date of Birth') ?></label>
<div class="input-box customer-dob">
<?php
    $this->setDateInput('d',
        '<div class="dob-day" style="height: 60px !important; width: 40px !important; display: block !important; float: left !important; margin-bottom; 0px; margin-right: 15px">
             <input type="text" style="margin-bottom: 2px; width:25px;" id="' . $this->getFieldId('day') . '" name="' . $this->getFieldName('day') . '" value="' . $this->getDay() . '" title="' . $this->__('Day') . '" class="input-text validate-custom txt fs-14 op-i" ' . $this->getFieldParams() . ' />
             <label for="' . $this->getFieldId('day') . '" class="fs-12 txt">' . $this->__('&nbsp;&nbsp;&nbsp;Dia') . '</label>
         </div>'
    );

    $this->setDateInput('m',
        '<div class="dob-month" style="height: 60px !important; width: 40px !important; display: block !important; float: left !important; margin-bottom; 0px; margin-right: 15px">
             <input type="text" style="margin-bottom: 2px; width:25px;" id="' . $this->getFieldId('month') . '" name="' . $this->getFieldName('month') . '" value="' . $this->getMonth()  . '" title="' . $this->__('Month')  . '" class="input-text validate-custom txt fs-14 op-i" ' . $this->getFieldParams()  . ' />
             <label for="' . $this->getFieldId('month') . '" class="fs-12 txt">' . $this->__('&nbsp;&nbsp;M&ecirc;s')  . '</label>
         </div>'
    );

    $this->setDateInput('y',
        '<div class="dob-year" style="height: 60px !important; width: 60px !important; display: block; float: left !important; margin-bottom; 0px">
             <input type="text" style="margin-bottom: 2px; width:35px;" id="' . $this->getFieldId('year') . '" name="' . $this->getFieldName('year') . '" value="' . $this->getYear()  . '" title="' . $this->__('Year')  . '" class="input-text validate-custom txt fs-14 op-i" ' . $this->getFieldParams()  . ' />
             <label for="' . $this->getFieldId('year') . '" class="txt fs-12">' . $this->__('&nbsp&nbsp&nbsp;&nbsp;Ano')  . '</label>
         </div>'
    );
?>
    <?php echo $this->getSortedDateInputs() ?>
    <div class="dob-full" style="display:none;">
        <input type="hidden" id="<?php echo $this->getFieldId('dob')?>" name="<?php echo $this->getFieldName('dob')?>" />
    </div>

    <div class="validation-advice" style="display:none;"></div>
</div>
<script type="text/javascript">
//<![CDATA[
    var customer_dob = new Varien.DOB('.customer-dob', <?php echo $this->isRequired() ? 'true' : 'false' ?>, '<?php echo $this->getDateFormat() ?>');
//]]>
</script>
