<?php
/**
 *
 * @category   Inovarti
 * @package    Inovarti_Pagarme
 * @author     Suporte <suporte@inovarti.com.br>
 */
?>
<?php $_code=$this->getMethodCode() ?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <li style="display: none;">
        <input type="hidden" id="<?php echo $_code ?>_pagarme_card_hash" name="payment[pagarme_card_hash]" value="" />
        <select id="<?php echo $_code ?>_cc_type" title="<?php echo $this->__('Credit Card Type') ?>" style="display: none;">
            <option value=""><?php echo $this->__('--Please Select--') ?></option>
        <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
            <option value="<?php echo $_typeCode ?>"><?php echo $_typeName ?></option>
        <?php endforeach ?>
        </select>
    </li>
    <li>
        <ul class="form-list pagarme-payment-icons" id="<?php echo $_code ?>_types">
        <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
            <li class="<?php echo $_typeCode ?> on">
                <span><?php echo $_typeName ?></span>
            </li>
        <?php endforeach ?>
        </ul>
    </li>
    <li>
        <label for="<?php echo $_code ?>_installments" class="required"><em>*</em><?php echo $this->__('Installments') ?></label>
        <div class="input-box">
            <select id="<?php echo $_code ?>_installments" name="payment[installments]" title="<?php echo $this->__('Installments') ?>" class="required-entry validate-select" onchange="pagarmeValidateFields()">
                <option value=""><?php echo $this->__('--Please Select--') ?></option>
            <?php $_installments = $this->getInfoData('installments') ?>
            <?php foreach ($this->getInstallmentsAvailables() as $_installmentValue => $_installmentLabel): ?>
                <option value="<?php echo $_installmentValue ?>"<?php /* if($_installmentValue==$_installments): ?> selected="selected"<?php endif */ ?>><?php echo $_installmentLabel ?></option>
            <?php endforeach ?>
            </select>
            <input type="hidden" id="<?php echo $_code ?>_installment_description" name="payment[installment_description]" value="<?php echo $this->escapeHtml($this->getInfoData('installment_description')) ?>" />
        </div>
    </li>
    <li>
        <label for="<?php echo $_code ?>_cc_number" class="required"><em>*</em><?php echo $this->__('Credit Card Number') ?></label>
        <div class="input-box">
            <input type="text" id="<?php echo $_code ?>_cc_number" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text pagarme-only-number required-entry validate-pagarme-cc-number" onchange="pagarmeValidateFields()" maxlength="19" value="" />
        </div>
    </li>
    <li>
        <label for="<?php echo $_code ?>_cc_owner" class="required"><em>*</em><?php echo $this->__('Name on Card') ?></label>
        <div class="input-box">
            <input type="text" title="<?php echo $this->__('Name on Card') ?>" class="input-text required-entry" id="<?php echo $_code ?>_cc_owner" onchange="pagarmeValidateFields()" value="" />
        </div>
    </li>
    <li>
        <label for="<?php echo $_code ?>_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label>
        <div class="input-box">
            <div class="v-fix pagarme-cc-expr-month">
                <select id="<?php echo $_code ?>_expiration" class="month validate-pagarme-cc-exp" onchange="pagarmeValidateFields()">
                <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                    <option value="<?php echo $k?$k:'' ?>"><?php echo $v ?></option>
                <?php endforeach ?>
                </select>
            </div>
            <div class="v-fix pagarme-cc-expr-year">
                <span>/</span>
                <select id="<?php echo $_code ?>_expiration_yr" class="year" onchange="pagarmeValidateFields()">
                <?php foreach ($this->getCcYears() as $k=>$v): ?>
                    <option value="<?php echo $k?$k:'' ?>"><?php echo $v ?></option>
                <?php endforeach ?>
                </select>
            </div>
        </div>
    </li>
    <?php echo $this->getChildHtml() ?>
    <?php if($this->hasVerification()): ?>
    <li>
        <label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label>
        <div class="input-box">
            <div class="v-fix pagarme-cvv">
                <input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text pagarme-only-number cvv required-entry validate-pagarme-cc-cvn" id="<?php echo $_code ?>_cc_cid" maxlength="4" onchange="pagarmeValidateFields()" value="" />
                <div class="pagarme-cvv-tool-tip">
                    <img src="<?php echo $this->getSkinUrl('pagarme/images/icon_cvv.gif') ?>" class="pagarme-cvv-icon" />
                    <div class="pagarme-cvv-image"><img src="<?php echo $this->getSkinUrl('pagarme/images/cvv.gif') ?>" alt="<?php echo $this->__('Card Verification Number Visual Reference') ?>" title="<?php echo $this->__('Card Verification Number Visual Reference') ?>" /></div>
                    <span class="pagarme-cvv-tool-tip-arrow">&nbsp;</span>
                </div>
            </div>
        </div>
    </li>
    <?php endif; ?>
    <li>
        <label id="pagarme-cardhash-waiting" class="a-center" style="display:none;"><?php echo __('Just a moment ...'); ?></label>
        <label id="pagarme-cardhash-success" class="a-center" style="display:none;"><?php echo __('All right!'); ?></label>
    </li>
</ul>
<script type="text/javascript">
//<![CDATA[
    pagarmeValidateFields = function() {
        pagarmeCardNumber          = (document.getElementById( '<?php echo $_code ?>_cc_number' ).value);
        pagarmeCardInstallments    = (document.getElementById( '<?php echo $_code ?>_installments' ).value);
        pagarmeCardOwner           = (document.getElementById( '<?php echo $_code ?>_cc_owner' ).value);
        pagarmeCardExpiration      = (document.getElementById( '<?php echo $_code ?>_expiration' ).value);
        pagarmeCardExpirationYr    = (document.getElementById( '<?php echo $_code ?>_expiration_yr' ).value);
        pagarmeCardCid             = (document.getElementById( '<?php echo $_code ?>_cc_cid' ).value);

        if (!pagarmeCardNumber || !pagarmeCardInstallments || !pagarmeCardOwner || !pagarmeCardExpiration || !pagarmeCardExpirationYr || !pagarmeCardCid) {
            return false;
        }

        PagarMe.encryption_key = pagarme_encryption_key;
        var pagarmeCreditCard = new PagarMe.creditCard();

        pagarmeCreditCard.cardHolderName       = pagarmeCardOwner;
        pagarmeCreditCard.cardExpirationMonth  = pagarmeCardExpiration;
        pagarmeCreditCard.cardExpirationYear   = pagarmeCardExpirationYr;
        pagarmeCreditCard.cardNumber           = pagarmeCardNumber;
        pagarmeCreditCard.cardCVV              = pagarmeCardCid;

        var fieldErrors = pagarmeCreditCard.fieldErrors();
        var hasErrors = false;

        for(var field in fieldErrors) { hasErrors = true; break; }

        if (hasErrors) {
            return false;
        }

        pagarmeCreditCard.generateHash(function(cardHash) {
            $("<?php echo $_code ?>_pagarme_card_hash").setValue(cardHash);
        });
    };

    function convertBrandToMagentoIdentifier(brand) {
        switch (brand) {
            case 'visa': return 'VI';
            case 'mastercard': return 'MC';
            case 'amex': return 'AE';
            case 'aura': return 'AU';
            case 'jcb': return 'JCB';
            case 'diners': return 'DC';
            case 'discover': return 'DI';
            case 'hipercard': return 'HC';
            case 'elo': return 'EL';
        }

        return null
    }

    $(document).on('click','#onestepcheckout-place-order-button',function(){
        pagarmeValidateFields();
    });

    $(document).on('click','#lbonepage-place-order-btn',function(){
        pagarmeValidateFields();
    });

    $(document).on('click','#payment-continue',function(){
        pagarmeValidateFields();
    });

    Event.observe($('<?php echo $_code ?>_cc_cid'), 'keyup', function(){
        pagarmeValidateFields();
    })

    var changeElement = false;
    document.on('click', function(evt, elm){
        if (elm.match('#<?php echo $_code ?>_cc_number') || elm.match('#<?php echo $_code ?>_cc_owner') || elm.match('#<?php echo $_code ?>_cc_cid') ){
            changeElement = true;
        } else {
            if (changeElement) {
                pagarmeValidateFields();
                changeElement = false;
            }
        }
    });

    Event.observe($('<?php echo $_code ?>_installments'), 'change', function(){
        $(this.id.substr(0,this.id.indexOf('_installments')) + '_installment_description').value = this.selectedIndex > 0 ? this.options[this.selectedIndex].text : '';
    });

    Event.observe($('<?php echo $_code ?>_cc_number'), 'change', function(){
        var typesContainer = $(this.id.substr(0,this.id.indexOf('_cc_number')) + '_types');
        var ccTypeContainer = $(this.id.substr(0,this.id.indexOf('_cc_number')) + '_cc_type');
        var ccCidContainer = $(this.id.substr(0,this.id.indexOf('_cc_number')) + '_cc_cid');
        var ccNumber = this.value;
        var ccType;

        var brand = PagarMe.Validator.getCardBrand(ccNumber)
        ccType = convertBrandToMagentoIdentifier(brand) || '';
        ccTypeContainer.value = ccType;

        if (ccNumber) {
            typesContainer.select('li').invoke('removeClassName', 'on');
            if (ccType && ccType == ccTypeContainer.value) {
                typesContainer.down('.' + ccType).addClassName('on');
            }
        } else {
            typesContainer.select('li').invoke('addClassName', 'on');
        }

        if (ccCidContainer.value) {
            Validation.validate(ccCidContainer);
        }
    });

    Event.observe($('<?php echo $_code ?>_cc_number'), 'keyup', function(){
        fireEvent(this, 'change');
    });

    // allow only numbers
    $$('input.pagarme-only-number').find(function(input){
        Event.observe(input, 'keydown', function(e){
            var code = e.keyCode || e.which;
            var isOnlyNumber = ((code > 47 && code < 58 && e.shiftKey == false)
                || (code > 95 && code < 106)
                || (e.ctrlKey || code == 8 || code == 9 || code == 13 || code == 16 || code == 35 || code == 36 || code == 37 || code == 38 || code == 39 || code == 40 || code == 46));

            if (!isOnlyNumber) {
                e.stop();
            }
        });

        Event.observe(input, 'blur', function(e){
            this.value = this.value.replace(/[^0-9]/g, '');
        });

        // prevent menu from right click
        Event.observe(input, 'contextmenu', function(e){
            e.stop();
        })
    });

    $$('input[name="payment[method]"]').find(function(radio) {
        Event.observe(radio, 'change', function() {
            if(radio.value == '<?php echo $_code ?>') {
                fireEvent($('<?php echo $_code ?>_cc_number'), 'change');
            } else {
                $('<?php echo $_code ?>_types').select('li').invoke('addClassName', 'on');
            }
        });
    });

    // Fill the form
    if (typeof payment !== "undefined" && payment.currentMethod == 'pagarme_cc' && payment.pagarme_cc_data) {
        $H(payment.pagarme_cc_data).each(function(field){
            $(payment.currentMethod+'_'+field.key).value = field.value;
            fireEvent($(payment.currentMethod+'_'+field.key), 'change');
        });
    }

    fireEvent($('<?php echo $_code ?>_installments'), 'change');
//]]>
</script>
