<?php
/**
 * @var $this Mage_Tax_Block_Checkout_Grandtotal
 * @see Mage_Tax_Block_Checkout_Grandtotal
 */
?>
<?php if ($this->includeTax() && $this->getTotalExclTax()>=0):?>
<tr>
    <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
        <p class="fs-16 cor bold"><?php echo $this->helper('tax')->__('Grand Total Excl. Tax')?></p>
    </td>
    <td style="<?php echo $this->getStyle() ?>" class="a-right">
        <p class="fs-16 cor bold"><?php echo $this->helper('checkout')->formatPrice($this->getTotalExclTax()) ?></p>
    </td>
</tr>
<?php echo $this->renderTotals('taxes', $this->getColspan()); ?>
<tr>
    <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
        <p class="fs-16 cor bold"><?php echo $this->helper('tax')->__('Grand Total Incl. Tax')?></p>
    </td>
    <td style="<?php echo $this->getStyle() ?>" class="a-right">
        <p class="fs-16 cor bold"><?php echo $this->helper('checkout')->formatPrice($this->getTotal()->getValue()) ?></p>
    </td>
</tr>
<?php else:?>
<tr>
    <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
        <p class="fs-16 cor bold"><?php echo $this->getTotal()->getTitle() ?></p>
    </td>
    <td style="<?php echo $this->getStyle() ?>" class="a-right">
        <p class="fs-16 cor bold"><?php echo Mage::helper('checkout')->formatPrice(Mage::getModel('checkout/session')->getQuote()->getGrandTotal()); ?></p>
    </td>
</tr>
<?php endif;?>
