<?php
/**
 * @see Mage_Payment_Block_Info
 */
?>
<p><?php echo $this->htmlEscape($this->getMethod()->getTitle()) ?></p>

<?php if ($_specificInfo = $this->getSpecificInformation()):?>
    <?php foreach ($_specificInfo as $_label => $_value):?>
        <p><?php echo $this->escapeHtml($_label)?>: <br /><?php echo nl2br(implode($this->getValueAsArray($_value, true), "\n"))?></p>
    <?php endforeach; ?>
<?php endif;?>

<?php echo $this->getChildHtml()?>
