<?php
/**
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2012 Magento Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<div class="input-box">
    <input style="-webkit-borde-radius: 5px;-moz-border-radius: 5px;-o-border-radius: 5px;border-radius: 5px;padding: 6px 10px 5px;width: 92%;border-color: #f5f5f5;background: #f5f5f5;border: 1px solid #ddd;font-size:14px;color:#6e6e6e;max-width:353px;" type="text" placeholder="* <?php echo $this->__('Tax/VAT number') ?>" id="<?php echo $this->getFieldId('taxvat')?>" name="<?php echo $this->getFieldName('taxvat')?>" value="<?php //echo $this->htmlEscape($this->getCustomer()->getCpfcnpj()) ?><?php echo $this->escapeHtml($this->getTaxvat()) ?>" title="<?php echo $this->__('Tax/VAT number') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('taxvat') ?>" <?php echo $this->getFieldParams() ?> />
</div>
<br />