<?php
/**
 *
 * @category   Inovarti
 * @package    Inovarti_Onestepcheckout
 * @author     Suporte <suporte@inovarti.com.br>
 */
?><div id="onestepcheckout-review-coupon">
<?php if ($this->canShow()): ?>
    <div class="coupon-message-container" style="overflow:hidden;height:0px;margin-bottom:10px;"></div>
    <div class="coupon-code-form">
        <div style="  overflow: hidden;height: 100px;">
            <div class="step-title"><h2>CUPOM DE DESCONTO</h2></div>
            <input class="d-b op-i txt fs-14 input-text<?php if ($this->getConfig()->isApplyCouponButton()) : ?> with-buttons<?php endif; ?>" style="margin-bottom:5px;" id="coupon_code" name="coupon_code" value="<?php echo $this->getCouponCode(); ?>" />
            <?php if ($this->getConfig()->isApplyCouponButton()) : ?>
                <button type="submit" class="bt3 radius cor-sec fs-11 tt-u bold td-n button" id="onestepcheckout-coupon-code-apply-btn" onclick="return false;"<?php if ($this->getCouponCode()) : ?> style="display:none;"<?php endif; ?>><?php echo $this->__('Apply Coupon'); ?></button>
                <button type="submit" class="bt3 radius cor-sec fs-11 tt-u bold td-n button" id="onestepcheckout-coupon-code-cancel-btn" onclick="return false;"<?php if (!$this->getCouponCode()) : ?> style="display:none;"<?php endif; ?>><?php echo $this->__('Cancel Coupon'); ?></button>
            <?php endif; ?>
        </div>
    </div>
    <script type="text/javascript">
        var OSCReviewCoupon = new OnestepcheckoutReviewCoupon({
            isCouponApplied: <?php echo ($this->getCouponCode()) ? 'true' : 'false'; ?>,
            isApplyCouponButton: <?php echo ($this->getConfig()->isApplyCouponButton()) ? 'true' : 'false'; ?>,
            applyCouponButtonSelector: '#onestepcheckout-coupon-code-apply-btn',
            cancelCouponButtonSelector: '#onestepcheckout-coupon-code-cancel-btn',
            msgContainerSelector: '.coupon-message-container',
            applyCouponUrl: '<?php echo $this->getApplyCouponAjaxUrl(); ?>',
            cancelCouponUrl: '<?php echo $this->getCancelCouponAjaxUrl(); ?>',
            couponCodeInput: 'coupon_code',
            successMessageBoxCssClass: 'onestepcheckout-success-msg',
            errorMessageBoxCssClass: 'onestepcheckout-error-msg',
            jsErrorMsg: <?php echo Zend_Json::encode($this->__("Oops something's wrong")); ?>,
            jsSuccessMsg: <?php echo Zend_Json::encode($this->__("Ok")); ?>
        });
    </script>
<?php endif; ?>
</div>