<?php
/**
 * Customer login form template
 *
 * @see app/design/frontend/base/default/template/customer/form/login.phtml
 */
/** @var $this Mage_Customer_Block_Form_Login */
?>
    <div id="colunas12" class="m-top">
    </div>
    
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form">
  <?php echo $this->getBlockHtml('formkey'); ?>
    <div id="colunas6">
    	<h2 class="cor bold fs-25"><?php echo $this->__('New Customers') ?></h2><br />
        <p class="fs-14"><?php //echo $this->__('By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.') ?>Primeira vez em nossa loja?<br />
Crie uma conta! Voc&ecirc; poder&aacute; finalizar suas compras com mais agilidade, <br />acompanhar seus pedidos, guardar os dados de envio, dentre outras vantagens.<br /> &Eacute; f&aacute;cil e muito r&aacute;pido.</p><br />
        <button type="button" title="<?php echo $this->__('Create an Account') ?>" class="button bt tt-u fs-14 radius cor-sec bold td-n" onclick="window.location='<?php echo Mage::helper('persistent')->getCreateAccountUrl($this->getCreateAccountUrl()) ?>';"><?php echo $this->__('Create an Account') ?></button>
    
    </div>
            
    <div id="colunas4">
    	<h2 class="cor bold fs-25"><?php echo $this->__('Registered Customers') ?></h2><br />
        <p class="fs-14"><?php //echo $this->__('If you have an account with us, please log in.') ?>J&aacute; fez o seu cadastro?<br />Para acessar uma conta, informe seus dados.</p><br />
        <label for="email" class="required fs-11 txt"><em>*</em><?php echo $this->__('Email Address') ?></label><br />
        <input type="text" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email f-l d-b op-i txt fs-14" title="<?php echo $this->__('Email Address') ?>" /><br /><br />
        <label for="pass" class="required fs-11 txt"><em>*</em><?php echo $this->__('Password') ?></label><br />
        <input type="password" name="login[password]" class="input-text required-entry validate-password f-l d-b op-i txt fs-14" id="pass" title="<?php echo $this->__('Password') ?>" /><br /><br /><br />
        <?php echo $this->getChildHtml('form.additional.info'); ?>
        <?php echo $this->getChildHtml('persistent.remember.me'); ?>
        <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
        <p class="required fs-10"><?php echo $this->__('* Required Fields') ?></p><br />
        <button type="submit" class="button bt radius cor-sec tt-u fs-14 bold td-n" title="<?php echo $this->__('Login') ?>" name="send" id="send2"><?php echo $this->__('Login') ?></button><br /><br />
        <a href="<?php echo $this->getForgotPasswordUrl() ?>" class="cor fs-12">Esqueci a minha senha<?php //echo $this->__('Forgot Your Password?') ?></a>
    </div>

        <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
            <input name="context" type="hidden" value="checkout" />
        <?php endif; ?>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('login-form', true);
    //]]>
    </script>
<div id="colunas12"></div>