<?php
/**
 */
?>
<?php
/**
 * @see Mage_Page_Block_Template_Links
 */
?>
<?php $collection = Mage::getModel('cms/page')->getCollection()->addStoreFilter(Mage::app()->getStore()->getId());?>
<?php  $collection->getSelect()->where('is_active = 1'); ?>
<ul id="menu-footer" class="bold fs-13 cor-sec">
	<?php foreach ($collection as $page): ?>
	<?php $PageData = $page->getData(); ?>
	<?php //print_r($PageData);?>
	<?php if($PageData['identifier']!='no-route' && $PageData['identifier']!='enable-cookies' && $PageData['identifier']!='home') { ?>
	<li>
		<a href="<?php echo Mage::getBaseUrl().$PageData['identifier']?>"><?php echo $PageData['title'] ?></a>
	</li>
	<?php } ?>
	<?php endforeach; ?>
</ul>

<?php $_links = $this->getLinks(); ?>
<?php if(count($_links)>0): ?>
<ul id="menu-footer" class="bold fs-13 cor-sec m-auto">
    <?php foreach($_links as $_link): ?>
        <?php if ($_link instanceof Mage_Core_Block_Abstract):?>
            <?php echo $_link->toHtml() ?>
        <?php else: ?>
            <li<?php if($_link->getIsFirst()||$_link->getIsLast()): ?> class="<?php if($_link->getIsFirst()): ?>first<?php endif; ?><?php if($_link->getIsLast()): ?> last<?php endif; ?>"<?php endif; ?> <?php echo $_link->getLiParams() ?>><?php echo $_link->getBeforeText() ?><a href="<?php echo $_link->getUrl() ?>" title="<?php echo $_link->getTitle() ?>" <?php echo $_link->getAParams() ?>><?php echo $_link->getLabel() ?></a><?php echo $_link->getAfterText() ?></li>
        <?php endif;?>
    <?php endforeach; ?>
</ul>
<?php endif; ?>
