<?php
/**
 * Magmodules.eu - http://www.magmodules.eu - info@magmodules.eu
 * =============================================================
 * NOTICE OF LICENSE [Single domain license]
 * This source file is subject to the EULA that is
 * available through the world-wide-web at:
 * http://www.magmodules.eu/license-agreement/
 * =============================================================
 * @category    Magmodules
 * @package     Magmodules_Snippets
 * @author      Magmodules <info@magmodules.eu>
 * @copyright   Copyright (c) 2015 (http://www.magmodules.eu)
 * @license     http://www.magmodules.eu/license-agreement/  
 * =============================================================
 */

 $breadcrumbs = Mage::app()->getLayout()->getBlock('breadcrumbs'); 
 $json_breadcrumbs = Mage::helper('snippets')->getJsonBreadcrumbs($breadcrumbs);
 
 if($json_breadcrumbs) {
 	echo '<script type="application/ld+json">[' . json_encode($json_breadcrumbs) . ']</script>';
 }
