<?php
/**
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2012 Magento Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<div id="colunas12" class="m-top">
    <h1 class="cor bold"><?php echo $this->__('Forgot Your Password?') ?></h1>
</div>
<div id="colunas12">
        <h2 class="legend txt bold fs-14"><?php echo $this->__('Retrieve your password here') ?></h2>
        <p class="txt fs-14"><?php echo $this->__('Please enter your email address below. You will receive a link to reset your password.') ?></p>
</div>
<div id="colunas4">
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getUrl('*/*/forgotpasswordpost') ?>" method="post" id="form-validate">
    <div class="fieldset">
        <ul class="form-list">
            <li>
                <label for="email_address" class="required txt fs-12"><em>*</em><?php echo $this->__('Email Address') ?>:</label>
                <div class="input-box">
                    <input type="text" name="email" alt="email" id="email_address" class="input-text required-entry validate-email d-b op-i txt fs-12" value="<?php echo $this->htmlEscape($this->getEmailValue()) ?>" />
                </div>
            </li>
            <?php echo $this->getChildHtml('form.additional.info'); ?>
        </ul>
        <br />
        <p class="required txt fs-12"><?php echo $this->__('* Required Fields') ?></p>
        <br />
        <button type="submit" title="<?php echo $this->__('Submit') ?>" class="button bt radius cor-sec tt-u fs-14 bold td-n"><?php echo $this->__('Submit') ?></button>
    </div>
</form>
</div>
<div id="colunas12">
	<a class="fs-12 cor" href="<?php echo $this->helper('customer')->getLoginUrl() ?>"><small>&laquo; </small><?php echo $this->__('Back to Login') ?></a></p>
</div>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
//]]>
</script>
