<?php
/**
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2012 Magento Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<div id="colunas12" class="m-top">
    <h1 class="cor bold"><?php echo $this->__('Reset a Password'); ?></h1>
</div>
<div id="colunas12">
<?php echo $this->getMessagesBlock()->getGroupedHtml(); ?>
<form action="<?php echo $this->getUrl('*/*/resetpasswordpost', array('_query' => array('id' => $this->getCustomerId(), 'token' => $this->getResetPasswordLinkToken()))); ?>" method="post" id="form-validate">
	
    <div class="fieldset">
        <ul class="form-list">
            <li class="fields">
                <div class="field short">
                    <label for="password" class="required txt fs-14"><em>*</em><?php echo $this->__('New Password'); ?>:</label>
                    <div class="input-box">
                        <input type="password" class="input-text required-entry validate-password d-b op-i txt fs-14" name="password" id="password" />
                    </div>
                </div>
                <br />
                <div class="field short">
                    <label for="confirmation" class="required fs-14 txt"><em>*</em><?php echo $this->__('Confirm New Password'); ?>:</label>
                    <div class="input-box">
                        <input type="password" class="input-text required-entry validate-cpassword d-b op-i txt fs-14" name="confirmation" id="confirmation" />
                    </div>
                </div>
            </li>
        </ul>
    </div>
    <br />
    <div class="buttons-set">
        <p class="required txt fs-12"><?php echo $this->__('* Required Fields'); ?></p>
        <br />
        <button type="submit" title="<?php echo $this->__('Reset a Password'); ?>" class="button bt fs-12 d-b cor-sec bold tt-u radius td-n"><?php echo $this->__('Reset a Password'); ?></button>
    </div>
</form>
<script type="text/javascript">
/*<![CDATA[*/
    var dataForm = new VarienForm('form-validate', true);
/*]]>*/
</script>
</div>