<?php

/**
 *
 * NOTICE OF LICENSE
 *
 * Todos direitos reservados para Thirdlevel | ThirdLevel All Rights Reserved
 *
 * @company   	ThirdLevel
 * @package    	MercadoLivre
 * @author      André Fuhrman (andrefuhrman@gmail.com)
 * @copyright  	Copyright (c) ThirdLevel [http://www.thirdlevel.com.br]
 * 
 */
?>
<script src="<?php echo $this->getJsUrl('jquery/jquery.js'); ?>"></script>
<script src="<?php echo $this->getJsUrl('chico/chico-0.11.js'); ?>"></script>
<script src="<?php echo $this->getJsUrl('jstree/jquery.jstree.js'); ?>"></script>
<script type="text/javascript">
//<![CDATA[
		
		
		var $j = jQuery.noConflict();

//]]>
        
</script>