<script type='text/javascript'>
Adroll = function() { ; }
Adroll.whats_this = function() {
    window.alert("In order for the extension to function properly, your store's configuration cache must be cleared. By leaving this box checked, you acknowledge that AdRoll will automatically clear your configuration cache. If unchecked, the extension will not function until cache is cleared manually. For more information on Magento cache: http://www.magentocommerce.com/wiki/modules_reference/english/mage_adminhtml/system_cache/index");
    }
</script>
<div id="adroll">
    <div id="adroll-header">
        <h1>AdRoll</h1>
        <h2>LiquidAds</h2>
        <h3>Magento Connect Extension</h3>
        <div class="clear"></div>
    </div>

    <div id="adroll-signup">
        <form method='post' action="<?php echo $this->getUrl('*/*/advertisables')?>">
            <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
            <input name="form" type="hidden" value="existing" />
            <h1>Link Your AdRoll Account</h1>

            <ul>
                <li>
                    <label for="email">Email Address <em>Use your existing AdRoll username/email</em></label>
                    <input type="text" name="email" id="email" /> 
                </li>
                <li>
                    <label for="password">Password <em>(<a href="https://www.adroll.com/account/lostpassword" target="_blank">Forgot Password?)</a></em></label>
                    <input type="password" name="password" id="password" /> 
                </li>
                <li>
                    <input class="adroll-checkbox" type="checkbox" name="flush_cache" checked="checked" /> 
                    <label class="adroll-checkbox">Clear Magento Cache <em>(<a href="#" onclick="Adroll.whats_this();">what's this?</a>)</em></label>
                    <div class="clear"></div>
                </li>
                <li id="adroll-terms">
                    <p>
                        By submitting this form and creating an account, 
                        you accept our 
                        <a href="http://www.adroll.com/about/terms" target="_blank">Terms and Conditions</a>.
                    </p>
                </li>
            </ul>
        
            <div id="adroll-form-footer">
                <input type="submit" id="adroll-submit" value="Sign In" /> 
                <div class="clear"></div>
            </div>
        </form>

        <a class="adroll-subtle-button" href="<?php echo $this->getUrl('*/*/new')?>" style="margin-top: 30px;">Need an account? Create a new AdRoll account.</a>
    </div>


    <div id="adroll-showcase">
        <div id="adroll-liquid-box">
            <h2>Example LiquidAd</h2>
            
            <!-- LIQUID AD -->
             <object
                classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000"
                codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab"
                width="300"
                height="250"
                id="eyefly">
                <param name="movie" value="https://s.adroll.com/magento/LiquidAdExample.swf" />
                <param name="FlashVars" value="demo=1"/>
                <embed
                    src="https://s.adroll.com/magento/LiquidAdExample.swf"
                    width="300"
                    height="250"
                    name="eyefly"
                    type="application/x-shockwave-flash"
                    pluginspage="http://www.adobe.com/go/getflashplayer"
                    FlashVars="demo=1"
                    />
              </object>
        </div>
        
        <p>
            <strong>AdRoll LiquidAds</strong> seamlessly integrate your site's product 
            images and branding into a personalized ad unit that looks 
            as incredible as it performs.
        </p>
    </div>
    <div class="clear"></div>
</div>
