<?php
/**
 *
 * @category   Inovarti
 * @package    Inovarti_Onestepcheckout
 * @author     Suporte <suporte@inovarti.com.br>
 */
?>
<?php if($this->getTitle()): ?>
<div id="colunas9">
        <h1 class="cor bold"><?php echo $this->getTitle() ?></h1>
</div>
<?php endif; ?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getSaveUrl() ?>" method="post" id="form-validate">
<div id="colunas4">
    <div class="fieldset">
    <?php echo $this->getBlockHtml('formkey')?>
    <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
    <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
        <ul class="form-list">
            <li class="fields">
                <?php echo $this->getNameBlockHtml() ?>
            </li>
            <?php if (Mage::helper('onestepcheckout/config')->isCompany()): ?>
            <li class="short wide">
                <label for="company" class="fs-12 txt bold"><?php echo $this->__('Company') ?></label>
                <input type="text" name="company" id="company" title="<?php echo $this->__('Company') ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>" class="input-text d-b op-i txt fs-14 <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" />
            </li>
            <?php endif; ?>
            <li class="short">
                <label for="telephone" class="fs-12 txt bold required"><em>*</em><?php echo $this->__('Telephone') ?></label>
                <input type="text" name="telephone" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text d-b op-i txt fs-14 <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" id="telephone" />
            </li>
			<li class="short">
                <label for="zip" class="f-l fs-12 txt bold required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label> <a class="f-l cor fs-12 nao-sei-cep" style="margin:1px 0 0 5px;" href="#" onclick="popWin('http://m.correios.com.br/movel/buscaCep.do', 'I forgot my zipcode', 'width=360,height=370,left=200,top=50,location=no,status=yes,scrollbars=yes,resizable=yes'); return false;"><?php echo $this->__('What is my postcode?') ?></a>
                <input type="text" name="postcode" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" id="postcode" class="input-text d-b op-i txt fs-14 <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" onblur="buscaCep()"/>
			</li>
        <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
            <li class="short wide">
                <label for="street_1" class="fs-12 txt bold required"><em>*</em><?php echo $this->__('Street Address') ?></label>
                <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" title="<?php echo $this->__('Street Address') ?>" id="street_1" class="input-text d-b op-i txt fs-14 <?php echo $_streetValidationClass ?>" />
            </li>
        
            <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
            <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
            <li class="short wide">
                <label for="street<?php echo $_i ?>" class="txt fs-12 bold required" <?php if ($_i != 3): ?> <?php endif; ?>><?php if ($_i != 3): ?> <em>*</em> <?php endif; ?><?php echo $this->__('Street Address '.$_i) ?></label>
                    <input type="text" name="street[<?php echo $_i ?>]" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>" title="<?php echo $this->__('Street Address '.$_i) ?>" id="street_<?php echo $_i ?>" class="input-text d-b op-i txt fs-14 <?php if ($_i != 3): ?>required-entry<?php endif; ?>"  />
            </li>
            <?php endfor; ?>
            <?php if ($this->helper('customer/address')->isVatAttributeVisible()) : ?>
            <li class="short wide">
                <label class="fs-12 txt bold" for="vat_id"><?php echo $this->__('VAT Number') ?></label>
                <input type="text" name="vat_id" value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()) ?>" title="<?php echo $this->__('VAT Number') ?>" id="vat_id" class="input-text d-b op-i txt fs-14 <?php echo $this->helper('customer/address')->getAttributeValidationClass('vat_id') ?>" />
            </li>
            <?php endif; ?>
            <li class="short fields">
                <label for="city" class="txt fs-12 bold required"><em>*</em><?php echo $this->__('City') ?></label>
                <input type="text" name="city" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>"  title="<?php echo $this->__('City') ?>" class="input-text d-b op-i txt fs-14 <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="city" />
            </li>

            <li class="short fields">
                <label for="region_id" class="txt fs-12 bold required"><em>*</em><?php echo $this->__('State/Province') ?></label>
                <select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
                   <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                </select>
                <script type="text/javascript">
                //<![CDATA[
                    $('region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                //]]>
                </script>
                <input type="text" id="region" name="region" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>"  title="<?php echo $this->__('State/Province') ?>" class="input-text d-b op-i txt fs-14 <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" />
            </li>
            <li class="short" style="display:none;">
				<label for="country" class="txt fs-12 bold required"><em>*</em><?php echo $this->__('Country') ?></label>
				<?php echo $this->getCountryHtmlSelect() ?>
            </li>
            <li<?php if($this->canSetAsDefaultBilling()) echo ' class="control"' ?>>
                <?php if($this->isDefaultBilling()): ?>

                <?php elseif($this->canSetAsDefaultBilling()): ?>
                    <input type="checkbox" id="primary_billing" name="default_billing" value="1" title="<?php echo $this->__('Use as My Default Billing Address') ?>" class="checkbox" /><label for="primary_billing"><?php echo $this->__('Use as my default billing address') ?></label>
                <?php else: ?>
                    <input type="hidden" name="default_billing" value="1" />
                <?php endif; ?>
            </li>
            <li<?php if($this->canSetAsDefaultShipping()) echo ' class="control"' ?>>
                <?php if($this->isDefaultShipping()): ?>
                    <strong><?php echo $this->__('Default Shipping Address') ?></strong>
                <?php elseif($this->canSetAsDefaultShipping()): ?>
                    <input type="checkbox" id="primary_shipping" name="default_shipping" value="1" title="<?php echo $this->__('Use as My Default Shipping Address') ?>" class="checkbox" /><label for="primary_shipping"><?php echo $this->__('Use as my default shipping address') ?></label>
                <?php else: ?>
                    <input type="hidden" name="default_shipping" value="1" />
                <?php endif; ?>
            </li>
        </ul>
    </div>
    <div class="clear buttons-set">
        <p class="f-l required"><?php echo $this->__('* Required Fields') ?></p><br />
        <button data-action="save-customer-address" type="submit" title="<?php echo $this->__('Save Address') ?>" class="button bt radius cor-sec tt-u fs-14 bold td-n"><span class="cor-sec"><?php echo $this->__('Save Address') ?></span></button>
    </div>
</div>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
    Validation.add('validate-zip-br', '<?php echo $this->__('Please enter a valid zip code. e.g. 12345678.') ?>', function(v) {
        return Validation.get('IsEmpty').test(v) || /(^\d{8}$)|(^\d{5}-\d{3}$)/.test(v);
    });
    Validation.add('validate-phone-br', '<?php echo $this->__('Please enter a valid phone number. for example, (xx) x4567-8900.') ?>', function(v) {
        return Validation.get('IsEmpty').test(v) || /^(\()?\d{2}(\))?(-|\s)?\d{5}(-|\s)\d{4}|(\()?\d{2}(\))?(-|\s)?\d{4}(-|\s)\d{4}$/.test(v);
    });
    if (jQuery('#telephone')) {
        jQuery('#telephone').addClass('validate-phone-br');
        jQuery('#telephone').on('keyup', function(event) {
            this.maxLength = 15;
            mascara(this, mtel);
        });
    }
    if (jQuery('#fax')) {
        jQuery('#fax').addClass('validate-phone-br');
        jQuery('#fax').on('keyup', function(event) {
            this.maxLength = 15;
            mascara(this, mtel);
        });
    }
    if (jQuery('#postcode')) {
        jQuery('#postcode').addClass('validate-zip-br');
        jQuery('#postcode').on('keyup', function(event) {
            this.maxLength = 8;
            mascara(this, sonumeros);
        });
    }
    if (jQuery('#street_1')) {
        jQuery('#street_1').on('keyup', function(event) {
            this.maxLength = 40;
        });
    }
    if (jQuery('#street_2')) {
        jQuery('#street_2').on('keyup', function(event) {
            this.maxLength = 5;
        });
    }
    if (jQuery('#street_3')) {
        jQuery('#street_3').on('keyup', function(event) {
            this.maxLength = 20;
        });
    }
    if (jQuery('#street_4')) {
        jQuery('#street_4').on('keyup', function(event) {
            this.maxLength = 20;
        });
    }
    if (jQuery('#city')) {
        jQuery('#city').on('keyup', function(event) {
            this.maxLength = 30;
        });
    }
//]]>
</script>
