<?php
/**
 *
 * NOTICE OF LICENSE
 *
 * Todos direitos reservados para Thirdlevel | ThirdLevel All Rights Reserved
 *
 * @company   	ThirdLevel
 * @package    	MercadoLivre
 * @author      André Fuhrman (andrefuhrman@gmail.com)
 * @copyright  	Copyright (c) ThirdLevel [http://www.thirdlevel.com.br]
 * 
 */
?>
<center>
<?php
echo Mage::helper('mercadolivre')->__('To autorize this application at Mercadolivre click on the link below:'); ?>
<br /><br />
<a href="<?php echo $this->getLink(); ?>" target="_self"><?php echo Mage::helper('mercadolivre')->__('Authorize this application at MercadoLivre'); ?></a>
</center>





