<?php
/**
 *
 * NOTICE OF LICENSE
 *
 * Todos direitos reservados para Thirdlevel | ThirdLevel All Rights Reserved
 *
 * @company   	ThirdLevel
 * @package    	MercadoLivre
 * @author      André Fuhrman (andrefuhrman@gmail.com)
 * @copyright  	Copyright (c) ThirdLevel [http://www.thirdlevel.com.br]
 *
 */
 
 

$rates = $this->getShippingRates();

if(is_array($rates)){ ?>
<form action="<?php  echo $this->getSaveUrl() ?>" method="post" id="form-validate" name="shipping" >
 <dl class="mp-methods">
    <div id="mperror" class="error-msg" style="display:none;"><?php echo $this->__('É necessário escolher uma opção de envio') ;?></div>
    
    	<?php foreach($rates as $key => $value): ?>  	
    	<dt><?php echo($value['title']);?></dt>    		
    		<?php if(isset($value['methods'])): ?>
    			<ul>
		    	<?php foreach ($value['methods'] as $subkey => $subvalue):?>
		  		<li><dd><input type=radio name="shipping_method"  value="<?php echo $key ."_". $subkey .':'. $subvalue['price'] .'/'. $subvalue['title'];?>">
		  		<label for="s_method_<?php echo $key .'_'. $subkey .':'. $subvalue['price'] .'/'. $subvalue['title'];?>">	
		  			<?php echo $subvalue['title'] . '( '. $subvalue['price_formatted']  . ' )'; ?>
		  		</label>	
		  		</dd></li>
		  		<?php endforeach; ?>
		  		</ul>
		  		<?php else: ?>
		  		<ul class="messages"><li class="error-msg"><?php echo $value['error'] ; ?></li></ul>
		  	<?php endif;?>
    	 
    <?php endforeach; ?>
    <div class="buttons-set">
        <button type="submit" title="<?php echo $this->__('Continue') ?>" class="button"><span><span><?php echo $this->__('Save') ?></span></span></button>
    </div>
    <p><i><?php echo Mage::helper('mercadolivre')->__('Refresh Order Page to see Shipping Method Updated') ?></i></p>
</form>
<?php

   } else {
   echo '<ul class="messages"><li class="error-msg">'.$rates.'</li></ul>';
   }
 ?>








