<?php
/**
 *
 * NOTICE OF LICENSE
 *
 * Todos direitos reservados para Thirdlevel | ThirdLevel All Rights Reserved
 *
 * @company   	ThirdLevel
 * @package    	MercadoLivre
 * @author      André Fuhrman (andrefuhrman@gmail.com)
 * @copyright  	Copyright (c) ThirdLevel [http://www.thirdlevel.com.br]
 * 
 */
?>
<script>
window.onload = window.parent.modal.hide() ;
</script>
                    
<center>
<?php echo Mage::helper('mercadolivre')->__('Your module is now authorized with Mercadolivre'); ?>
</center>





